language: groovy
groovy:
    - 2.3.9
jdk:
    - oraclejdk8
    
before_install:
    - wget http://dl.bintray.com/groovy/maven/groovy-binary-2.3.9.zip
    - unzip groovy-binary-2.3.9.zip
    - export PATH=$PWD/groovy-2.3.9/bin:$PATH

script:
    - groovy -version
    - groovy FizzBuzzSpec.groovy
